name: spaceapps-mo-data
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - iris
  - xarray
  - cfgrib
  - iris-grib
  - cartopy
  - pandas
  - numpy
  - matplotlib
  - scipy
  - cf-units
  - ipykernel
  - ipython
  - nc-time-axis
