name: spaceapps-mo-ml-intro
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab>=3.4.7
  - pandas>=1.5.0
  - numpy>=1.23.3
  - matplotlib>=3.6.0
  - scipy>=1.9.1
  - ipykernel>=6.16.0
  - ipython>=8.5.0
  - tensorflow>=2.0
  - scipy>=1.9.1
  - scikit-learn>=1.0.2
  
